//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// paint_res.rc

#define IDD_SIZE                            100

#define ID_OPEN                             100
#define ID_SAVE                             101
#define ID_EXIT                             102
#define ID_CUT                              103
#define ID_COPY                             104
#define ID_PASTE                            105
#define ID_DELETE                           106
#define ID_SELECT_ALL                       107
#define ID_SELECT                           108
#define ID_PENCIL                           109
#define ID_RECT                             110
#define ID_ELLIPSE                          111
#define ID_LINE                             112
#define ID_LINE_COLOR                       113
#define ID_FILL_COLOR                       114
#define ID_CANVAS_SIZE                      115

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     116
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
